import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "あれ、あったっけ？",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ChakraProvider>
          <Header/>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
