import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import Header from "./components/Header";
import Link from "next/link";

export const metadata: Metadata = {
  title: "あれ、あったっけ？",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ChakraProvider>
          <Link href="/manage">
            <Header />
          </Link>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
